sudo: required

# whitelist
branches:
  only:
   - gh-pages   

language: node_js
node_js:
  - "4.1"

before_script:
  - npm install -g json

script: json -f projects.json

notifications:
  hipchat:
    rooms:
      secure: yVKjoy/MZhAgQ6Fs3N7TZ0XZQzHzKfMcIKjSc+4BDKIHqce6/YwTyX628nfkhl05cCgzae06t09JILs2KYBcUTGLQTxN6t6i7onIPX4ueO3/MblcprzVP/7PL4FkxUUSxCF6FL33tPuexPLkHKqKJyYrwVhBUqnIGqYm2X0F++q5EHNk/ezXYEnz8FZKiWwYbF+XL8vj/9ev6DsmadKMl9YCxNhitzNIsAqCMF+73SjgESXQHt1YUdVVRvSnsehcOAZmp7Q6MPGAnrYRpRUo7imUJv35bXw1kfB92nYIDGysTl03bKzgxn0XFkWGFcPRnADCdPWfFY6jG0y+9Q4x87mjHEdj8UfcD5FOKa7PmcLnZskDZEqMObVsNxLlFagsje6An1b8s/bN515A26SNu4t/QXF52neaJf1Brc1AC1G2fvO1DN8KwJgQ9ydSi7Xru9eh/G70Bylb8wAhfzOdBf53YRRvsljFvMZJrCF4qStYLktu4Wnx3pxTxZeZblUdy4ZV0ujWjTYew6AFLmP0oNzyasxNkkQEiigncvE0oSyH5x7aIj0J2mgxaL6fQr16J9iQenZOipm9eIoIYrfWbd2JaHnQoqlEWWSpHcKf8DwM65b5kApFenhDdwpBPee90uPjegUzoG+jKoH6Me8v5k31DFJtIBSLrEZ6JuJuKHM=
